spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: mysql123
  messages:
    basename: i18n/messages

server:
  port: 80

mybatis-plus:
  configuration:
    log-impl:
      org.apache.ibatis.logging.stdout.StdOutImpl


